

spring:
  threads:
    virtual:
      enabled: true
  r2dbc:
    url: r2dbc:h2:mem:///dev;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    generate-ddl: false
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/dev
    username: sa
    password:
  sql:
    init:
      schema-locations: classpath:db/h2/schema.sql
      data-locations: classpath:db/h2/data.sql

logging:
  level:
    org:
      springframework:
        r2dbc: debug

